name: Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ${{ secrets.https://github.com/nikitakalmykov03/-Balenciaga.git }}/${{ github.repository }}:${{ github.sha }} .

      - name: Login to GitHub Packages
        run: echo ${{ secrets.nikitakalmykov03 }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Publish Docker image
        run: docker push ${{ secrets.https://github.com/nikitakalmykov03/-Balenciaga.git }}/${{ github.repository }}:${{ github.sha }}

      - name: Run Docker image
        run: docker run ${{ secrets.https://github.com/nikitakalmykov03/-Balenciaga.git }}/${{ github.repository }}:${{ github.sha }}



