name: Publish Docker image

on:
  push:
    branches: [main]

jobs: 
  login:
    runs-on: ubuntu-latest 
    steps:
      - name: Login to GitHub Container Registry 
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Package Registry
        run: docker push docker.pkg.github.com/${{ github.repository }}/${{ github.sha }}
      - name: Run Docker image
        run: docker run docker.pkg.github.com/${{ github.repository }}/${{ github.sha }}

